---
# common variables for all hosts

dotfiles_user: "{{ ansible_user_id }}"
dotfiles_home: "{{ ansible_env.HOME }}"

homebrew_install_url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
oh_my_zsh_install_url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"

configure_homebrew: true
configure_tmux: true
configure_neovim: true
configure_ghostty: true
configure_zsh: true
configure_bash: true
configure_cli_tools: true

common_cli_tools:
  - tmux
  - neovim
  - zsh
  - git
  - eza
  - zoxide
  - fzf
  - fd
  - ripgrep
  - bat
  - lazygit
  - jq
  - htop
  - tree
  - wget
  - curl
  - gh

config_directories:
  - "{{ dotfiles_home }}/.config"
  - "{{ dotfiles_home }}/.config/nvim"
  - "{{ dotfiles_home }}/.config/tmux"
  - "{{ dotfiles_home }}/.local/bin"
  - "{{ dotfiles_home }}/.local/share"
  - "{{ dotfiles_home }}/.local/state"
