---
# macos specific variables

homebrew_prefix: "{{ '/opt/homebrew' if ansible_machine == 'arm64' else '/usr/local' }}"

macos_applications:
  - spotify
  - ghostty
  - 1password
  - librewolf
  - obsidian
  - transmission
  - raycast
  - iina

configure_aerospace: true
configure_macos_settings: true
configure_hot_corners: true
configure_dock: true
configure_finder: true

# hot corners configuration
# possible values:
#  0: none
#  2: mission control
#  3: application windows
#  4: desktop
#  5: start screen saver
#  6: disable screen saver
#  7: dashboard
# 10: put display to sleep
# 11: launchpad
# 12: notification center
# 13: lock screen
hot_corner_top_left: 10      # put display to sleep
hot_corner_top_right: 5      # start screen saver
hot_corner_bottom_left: 0    # none
hot_corner_bottom_right: 0   # none

dock_icon_size: 48
dock_autohide: true
dock_orientation: "bottom"
dock_show_recents: false
finder_show_hidden_files: true
finder_show_extensions: true
finder_default_view: "Nlsv"  # list view
