---
# linux specific variables

homebrew_prefix: "/home/linuxbrew/.linuxbrew"

linux_system_packages:
  - build-essential
  - curl
  - git
  - wget

linux_gui_alternatives:
  spotify: "snap install spotify"
  obsidian: "snap install obsidian --classic"
  librewolf: "Use flatpak or AppImage"
  transmission: "apt install transmission-gtk"
