---
- name: Configure hot corner - top left
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: "{{ hot_corner_top_left }}"
  notify: restart dock

- name: Configure hot corner - top right
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tr-corner
    type: int
    value: "{{ hot_corner_top_right }}"
  notify: restart dock

- name: Configure hot corner - bottom left
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-corner
    type: int
    value: "{{ hot_corner_bottom_left }}"
  notify: restart dock

- name: Configure hot corner - bottom right
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-br-corner
    type: int
    value: "{{ hot_corner_bottom_right }}"
  notify: restart dock

# - name: Configure hot corner modifier - bottom right
#   community.general.osx_defaults:
#     domain: com.apple.dock
#     key: wvous-br-modifier
#     type: int
#     value: 0
#   notify: restart dock
