---
- name: restart dock
  ansible.builtin.command: killall Dock
  changed_when: false
  failed_when: false

- name: restart finder
  ansible.builtin.command: killall Finder
  changed_when: false
  failed_when: false
